### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'tracer')

### ISSUE THREAD

**Issue by knubie** [flow-storm/flow-storm-debugger#119]
A few months ago I was able to successfully test out vanilla FlowStorm in my project, but this time I wanted to try out the new ClojureScriptStorm version, however I'm running into an error during runtime (both in browser and Node.js).

```
core.js:1279 TypeError: Cannot read properties of undefined (reading 'tracer')
    at eval (features.cljs:3:1)
    at eval (<anonymous>)
    at goog.globalEval (core.js:430:11)
    at env.evalLoad (core.js:1387:12)
    at core.js:1506:12
```

Here is the contents of `features.cljs`:

```clj
(ns memo.features)

(goog-define WEBSITE-DEMO false)
```

And here is the contents of my `deps.edn` file:

```clj
{:paths ["src"]
 :deps {...}
 :aliases
 {:dev
                         ;; disable the official compiler
  {:classpath-overrides {org.clojure/clojurescript             nil}

   :extra-deps          {thheller/shadow-cljs                  {:mvn/version "2.25.10" ;; >= 2.25.4
                                                                :exclusions [org.clojure/clojurescript]}
                         ;; bring ClojureScriptStorm
                         com.github.flow-storm/clojurescript   {:mvn/version "RELEASE"}
                         ;; add FlowStorm runtime dep
                         com.github.flow-storm/flow-storm-inst {:mvn/version "RELEASE"}}
      :jvm-opts ["-Dcljs.storm.instrumentOnlyPrefixes=memo"
                  "-Dcljs.storm.instrumentEnable=true"
                  "-Dflowstorm.startRecording=false"]}}}

```

Any help troubleshooting would be appreciated!

**Comment by jpmonettas** [comment]
hi @knubie, that error seems to be related to your shadow-cljs.edn not containing the `flow-storm.storm-preload` as your first preload. Your shadow-cljs.edn should look something like this :

```clojure
{:deps {:aliases [:dev]}
 :nrepl {:port 9000}
 ...
 :builds
 {:memo {...
        :devtools {:preloads [flow-storm.storm-preload]
                   ...}}}}


``` 
assuming your build-id is called `:memo`.

**Comment by knubie** [comment]
Right you are @jpmonettas , I failed to RTFM. 😔 Thank you for the help, and thanks for flow storm!
