### ISSUE TITLE
Debugger fails to start

### ISSUE THREAD

**Issue by licht1stein** [flow-storm/flow-storm-debugger#191]
This happens in a larger of my projects (works fine on the same machine on a smaller project). It fails to launch both in vanilla and full-fledged mode. Trace:

```
Runtime index system started
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /home/mb/.openjfx/cache/21.0.4-ea+1/amd64/libprism_es2.so: libXxf86vm.so.1: cannot open shared object file: No such file or directory
java.lang.UnsatisfiedLinkError: /home/mb/.openjfx/cache/21.0.4-ea+1/amd64/libprism_es2.so: libXxf86vm.so.1: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2021)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:220)
	at com.sun.glass.utils.NDec 29, 2024 9:50:06 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @2d233b48'
Loading library glassgtk3 from resource failed: java.lang.UnsatisfiedLinkError: /home/mb/.openjfx/cache/21.0.4-ea+1/amd64/libglassgtk3.so: libXtst.so.6: cannot open shared object file: No such file or directory
java.lang.UnsatisfiedLinkError: /home/mb/.openjfx/cache/21.0.4-ea+1/amd64/libglassgtk3.so: libXtst.so.6: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2021)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:220)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:200)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:142)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:58)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$new$5(GtkApplication.java:173)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:162)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:40)
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:292)
	at javafx.application.Platform.startup(Platform.java:113)
	at flow_storm.debugger.ui.utils$init_toolkit$fn__12604.invoke(utils.clj:27)
	at flow_storm.debugger.ui.utils$init_toolkit.invokeStatic(utils.clj:26)
	at flow_storm.debugger.ui.utils$init_toolkit.invoke(utils.clj:24)
	at flow_storm.debugger.main$start_debugger.invokeStatic(main.clj:81)
	at flow_storm.debugger.main$start_debugger.invoke(main.clj:61)
	at clojure.lang.Var.invoke(Var.java:386)
	at flow_storm.runtime.debuggers_api$start_runtime.invokeStatic(debuggers_api.cljc:684)
	at flow_storm.runtime.debuggers_api$start_runtime.invoke(debuggers_api.cljc:672)
	at flow_storm.api$local_connect.invokeStatic(api.clj:85)
	at flow_storm.api$local_connect.invoke(api.clj:61)
	at flow_storm.api$local_connect.invokeStatic(api.clj:77)
	at flow_storm.api$local_connect.invoke(api.clj:61)
	at user$eval11896.invokeStatic(NO_SOURCE_FILE:12)
	at user$eval11896.invoke(NO_SOURCE_FILE:12)
	at clojure.lang.Compiler.eval(Compiler.java:7700)
	at nrepl.middleware.interruptible_eval$evaluator$run__1760$fn__1771.invoke(interruptible_eval.clj:106)
	at nrepl.middleware.interruptible_eval$evaluator$run__1760.invoke(interruptible_eval.clj:101)
	at nrepl.middleware.session$session_exec$session_loop__1839.invoke(session.clj:229)
	at nrepl.SessioJavaFX toolkit already initialized
Waiting for a dispatch-fn before dispatching events
Waiting for a dispatch-fn before dispatching events
```

alias:

```clojure
:storm {:classpath-overrides {org.clojure/clojure nil}
          :extra-deps {com.github.flow-storm/flow-storm-dbg {:mvn/version "4.0.2"}
                             com.github.flow-storm/clojure {:mvn/version "1.12.0"}}
          :jvm-opts ["-Dflowstorm.startRecording=false"
                     "-Dclojure.storm.instrumentEnable=true"
                     "-Dflowstorm.title=Storm"
                     "-Dflowstorm.theme=dark"
                     "-Dflowstorm.fileEditorCommand=emacsclient -n +<<LINE>>:0 <<FILE>>"
                     "-Dflowstorm.jarEditorCommand=emacsclient --eval '(let ((b (cider-find-file \"jar:file:<<JAR>>!/<<FILE>>\"))) (with-current-buffer b (switch-to-buffer b) (goto-char (point-min)) (forward-line (1- <<LINE>>))))'"]}
```

Any advice on how to solve this?

**Comment by jpmonettas** [comment]
Hi! Thanks for reporting the issue.
That is weird, the exception seams OS dependent, looks like it is failing to load some native libs when start JavaFX.

Are both projects running with the same JVM?
 
Can you share more details about your JVM, like `java -version`?

Can you also add here the `clj -Stree` and `clj -Spath` of both projects detailing the one which works and the one which doesn't?

**Comment by jpmonettas** [comment]
> The path has too much info about the companies behind the projects :(

No problem!

So I guess the issue isn't related to your projects nor the classpath nor flow-storm, but to the JVM and native libraries on that nix environment.

Here is a very small Clojure JavaFX project you can try to run in that Nix environment, it should also fail : 

```clojure
{:deps {org.openjfx/javafx-controls {:mvn/version "21.0.4-ea+1"}
        org.openjfx/javafx-base {:mvn/version "21.0.4-ea+1"}
        org.openjfx/javafx-graphics {:mvn/version "21.0.4-ea+1"}}}
```

src/main.clj
```clojure
(ns main
  (:import [javafx.application Platform]
           [javafx.scene Scene]
           [javafx.stage Stage]
           [javafx.scene.control Label]))

(defn -main []
  (Platform/startup (fn [] (println "JavaFX toolkit initialized")))
  (Platform/runLater
   (fn []
     (let [scene (Scene. (Label. "Hello world") 1024 768)
           stage (doto (Stage.)
                   (.setScene scene))]

       (.show stage)))))

```

Which you can run with `clj -M -m main`

It seams there have been similar issues reported on Nix https://github.com/NixOS/nixpkgs/issues/220470 and some hacks to solve them.

**Comment by licht1stein** [comment]
Thank you! I'll try it out and report 🙏

**Comment by licht1stein** [comment]
Tried it, here's the result:

```clojure
{:clojure.main/message
 "Execution error (UnsatisfiedLinkError) at java.lang.ClassLoader/loadLibrary (ClassLoader.java:2458).\nno glassgtk3 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib\n",
 :clojure.main/triage
 {:clojure.error/class java.lang.UnsatisfiedLinkError,
  :clojure.error/line 2458,
  :clojure.error/cause
  "no glassgtk3 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib",
  :clojure.error/symbol java.lang.ClassLoader/loadLibrary,
  :clojure.error/source "ClassLoader.java",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type java.lang.RuntimeException,
    :message
    "java.lang.UnsatisfiedLinkError: no glassgtk3 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib",
    :at
    [com.sun.javafx.tk.quantum.QuantumToolkit
     startup
     "QuantumToolkit.java"
     300]}
   {:type java.lang.UnsatisfiedLinkError,
    :message
    "no glassgtk3 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib",
    :at [java.lang.ClassLoader loadLibrary "ClassLoader.java" 2458]}],
  :trace
  [[java.lang.ClassLoader loadLibrary "ClassLoader.java" 2458]
   [java.lang.Runtime loadLibrary0 "Runtime.java" 916]
   [java.lang.System loadLibrary "System.java" 2059]
   [com.sun.glass.utils.NativeLibLoader
    loadLibraryInternal
    "NativeLibLoader.java"
    170]
   [com.sun.glass.utils.NativeLibLoader
    loadLibrary
    "NativeLibLoader.java"
    58]
   [com.sun.glass.ui.gtk.GtkApplication
    lambda$new$5
    "GtkApplication.java"
    173]
   [java.security.AccessController
    doPrivileged
    "AccessController.java"
    319]
   [com.sun.glass.ui.gtk.GtkApplication
    <init>
    "GtkApplication.java"
    162]
   [com.sun.glass.ui.gtk.GtkPlatformFactory
    createApplication
    "GtkPlatformFactory.java"
    40]
   [com.sun.glass.ui.Application run "Application.java" 146]
   [com.sun.javafx.tk.quantum.QuantumToolkit
    startup
    "QuantumToolkit.java"
    290]
   [com.sun.javafx.application.PlatformImpl
    startup
    "PlatformImpl.java"
    292]
   [javafx.application.Platform startup "Platform.java" 113]
   [main$_main invokeStatic "main.clj" 8]
   [main$_main invoke "main.clj" 7]
   [clojure.lang.AFn applyToHelper "AFn.java" 152]
   [clojure.lang.AFn applyTo "AFn.java" 144]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause
  "no glassgtk3 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib"}}
```

**Comment by jpmonettas** [comment]
Yeah, so it isn't related to FlowStorm, it can't run any javafx program because it can't find gassgtk3.

It says it is searching in `/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib`

In my Debian system it is here `/home/jmonetta/.openjfx/cache/21.0.4-ea+1/amd64/libglassgtk3.so`

You can maybe try to search for that library file (libglassgtk3.so) and if it is there somewhere, try run the little project like with this deps.edn : 

```clojure
{:deps {org.openjfx/javafx-controls {:mvn/version "21.0.4-ea+1"}
        org.openjfx/javafx-base {:mvn/version "21.0.4-ea+1"}
        org.openjfx/javafx-graphics {:mvn/version "21.0.4-ea+1"}}
 :aliases {:javafx {:jvm-opts ["-Djava.library.path=/usr/.../glass-folder/"]}}}
```  
Then you can run with `clj -M:javafx -m main` and the JVM should also look for libraries there.

But all this is quite hacky, there is probably a better way of running javafx application in Nix.

**Comment by jpmonettas** [comment]
I found on the JavaFX sources how it looks for these libraries https://github.com/openjdk/jfx/blob/master/modules/javafx.graphics/src/main/java/com/sun/glass/utils/NativeLibLoader.java#L113-L123

**Comment by jpmonettas** [comment]
@licht1stein Can we close this or is it still an issue?

**Comment by jpmonettas** [comment]
Closing it for now, please re-open if this is still an issue.
